### ISSUE TITLE
Add GET method for http tunneling

### ISSUE THREAD

**Issue by ingnelson** [tingtingths/tunnel.go#1]
Hello .

could you add a HTTP tunneling via GET method , please ? because my firewall blocks my connection if the HTTP request beging with CONNECT method.

I will wait your answer.

**Comment by tingtingths** [comment]
Hi,

The latest commit https://github.com/tingtingths/tunnel.go/commit/c08d75e94574ae2ef5fe94e8904a520c767db877 add a new `--method` argument to allows the use of different methods.

E.g. to allow using GET & CONNECT methods
`--method get,connect`


However, I would recommand you to enable encryption between the proxy client and the tunnel server. That way the firewall shouldn't be able to tell the method in use. 

Tony
